# Generated by Django 5.1.6 on 2026-08-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_drawresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
    ]
