# Generated by Django 5.1.6 on 2026-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('weight_category', models.CharField(max_length=50)),
                ('bracket_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('gender', 'weight_category')},
            },
        ),
    ]
